forward_addr = "ws://XX.X.X.XX:8080" # address of Pi module
max_tries = 3                        # max number of attempts to connect to the server
interval = 10                        # 100Hz in miliseconds
