name: Run unit tests

on:
    workflow_call
permissions:
    contents: read

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Setup Python 3.11
            uses: actions/setup-python@v3
            with:
                python-version: "3.11"
        # if future versions require any dependencies, install a requirements.txt here
          - name: Run tests
            run: python -m unittest
            
